{% set name = "e3sm_diags" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/e3sm_diags/archive/v{{ version }}.tar.gz
  sha256: 6b70c1911b5d50930f7441e91e5eb0864fe271e0ba9063680304f51308606270

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - e3sm_diags = acme_diags.acme_diags_driver:main
    - acme_diags = acme_diags.acme_diags_driver:main
    - e3sm_diags_vars = acme_diags.acme_diags_vars:main

requirements:
  host:
    - python
    - pip

  run:
    - python
    - cdp
    - cdms2
    - cdutil
    - genutil
    - cdtime
    - numpy
    - matplotlib-base
    - cartopy
    - beautifulsoup4
    - lxml
    - dask <=2.15.0

test:
  source_files:
    - tests/*
  imports:
    - acme_diags
  commands:
    - e3sm_diags --help
    - bash tests/test.sh

about:
  home: https://github.com/E3SM-Project/e3sm_diags
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Diagnostics package for the DOE's Energy Exascale Earth System Model
    (E3SM) project.
  doc_url: https://e3sm-project.github.io/e3sm_diags/docs/html/index.html
  dev_url: https://github.com/E3SM-Project/e3sm_diags

extra:
  recipe-maintainers:
    - xylar
    - chengzhuzhang
    - forsyth2
