{% set name = "e3sm_diags" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/e3sm_diags/archive/v{{ version }}.tar.gz
  sha256: 885c6d55cc88032acb78072981a53011499468ada6f38d9fe22a6a64ba05ff6f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - e3sm_diags = e3sm_diags.e3sm_diags_driver:main
    - e3sm_diags_vars = e3sm_diags.e3sm_diags_vars:main


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - beautifulsoup4
    - cartopy >=0.17.0
    - cartopy_offlinedata
    - cf-units
    - dask !=2024.12.0,!=2024.12.1
    - lxml
    - mache >=0.15.0
    - matplotlib-base >=3.8.2
    - netcdf4
    - output_viewer >=1.3.0
    - numpy >=2.0.0,<3.0.0
    - pywavelets
    - scipy
    - xarray >=2024.3.0
    - xcdat >=0.7.3,<1.0.0
    - xesmf >=0.8.7
    - xskillscore >=0.0.20

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - e3sm_diags
  commands:
    - e3sm_diags --help
    - pip check

about:
  home: https://github.com/E3SM-Project/e3sm_diags
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Diagnostics package for the DOE's Energy Exascale Earth System Model
    (E3SM) project.
  doc_url: https://e3sm-project.github.io/e3sm_diags/docs/html/index.html
  dev_url: https://github.com/E3SM-Project/e3sm_diags

extra:
  recipe-maintainers:
    - xylar
    - chengzhuzhang
    - forsyth2
    - tomvothecoder
