{% set name = "e3sm_diags" %}
{% set version = "2.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/e3sm_diags/archive/v{{ version }}.tar.gz
  sha256: 9da171a8b033d515a667f887815608e963c0cd8548bac6719cf156ad1574560d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - e3sm_diags = e3sm_diags.e3sm_diags_driver:main
    - e3sm_diags_vars = e3sm_diags.e3sm_diags_vars:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - beautifulsoup4
    - cartopy >=0.17.0
    - cartopy_offlinedata
    - cdms2 3.1.5
    - cdutil 8.2.1
    - dask
    - esmpy >=8.4.0
    - genutil 8.2.1
    - lxml
    - mache >=0.15.0
    - matplotlib-base
    - netcdf4
    - output_viewer >=1.3.0
    - numpy >=2.0.0,<3.0.0
    - scipy
    - shapely >=2.0.0,<3.0.0
    - xarray >=2024.03.0

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-cov
  source_files:
    - tests/*
  imports:
    - e3sm_diags
  commands:
    - e3sm_diags --help
    - export CHECK_IMAGES=False; bash tests/test.sh
    - pip check

about:
  home: https://github.com/E3SM-Project/e3sm_diags
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Diagnostics package for the DOE's Energy Exascale Earth System Model
    (E3SM) project.
  doc_url: https://e3sm-project.github.io/e3sm_diags/docs/html/index.html
  dev_url: https://github.com/E3SM-Project/e3sm_diags

extra:
  recipe-maintainers:
    - xylar
    - chengzhuzhang
    - forsyth2
    - tomvothecoder
