{% set name = "e3sm_diags" %}
{% set version = "2.6.1rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/e3sm_diags/archive/v{{ version }}.tar.gz
  sha256: 86027c14c4edfab79122dc094cfbd62a7657654460e5ddadcd9ada54aee62218

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - e3sm_diags = e3sm_diags.e3sm_diags_driver:main
    - e3sm_diags_vars = e3sm_diags.e3sm_diags_vars:main

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - cdp >=1.7.0
    - cdms2
    - cdutil
    - genutil
    - cdtime
    - numpy
    - netcdf4
    - matplotlib-base
    - cartopy
    - cartopy_offlinedata
    - beautifulsoup4
    - lxml
    - dask
    - scipy
    - output_viewer >=1.3.3

test:
  source_files:
    - tests/*
  imports:
    - e3sm_diags
  commands:
    - e3sm_diags --help
    - export CHECK_IMAGES=False; bash tests/test.sh

about:
  home: https://github.com/E3SM-Project/e3sm_diags
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Diagnostics package for the DOE's Energy Exascale Earth System Model
    (E3SM) project.
  doc_url: https://e3sm-project.github.io/e3sm_diags/docs/html/index.html
  dev_url: https://github.com/E3SM-Project/e3sm_diags

extra:
  recipe-maintainers:
    - xylar
    - chengzhuzhang
    - forsyth2
