{% set name = "e3sm_diags" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/e3sm_diags/archive/v{{ version }}.tar.gz
  sha256: ad44e9d851425aaebf62c4037d7fbc12aaf09e259c5ace4bb611495069dbee23

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - e3sm_diags = e3sm_diags.e3sm_diags_driver:main
    - e3sm_diags_vars = e3sm_diags.e3sm_diags_vars:main

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - pip
    - beautifulsoup4
    - cartopy
    - cartopy_offlinedata
    - cdp
    - cdms2
    - cdutil
    - genutil
    - lxml
    - mache
    - matplotlib-base
    - netcdf4
    - numpy
    - xarray

test:
  requires:
    - pip
  source_files:
    - tests/*
  imports:
    - e3sm_diags
  commands:
    - e3sm_diags --help
    - export CHECK_IMAGES=False; bash tests/test.sh
    - pip check

about:
  home: https://github.com/E3SM-Project/e3sm_diags
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Diagnostics package for the DOE's Energy Exascale Earth System Model
    (E3SM) project.
  doc_url: https://e3sm-project.github.io/e3sm_diags/docs/html/index.html
  dev_url: https://github.com/E3SM-Project/e3sm_diags

extra:
  recipe-maintainers:
    - xylar
    - chengzhuzhang
    - forsyth2
    - tomvothecoder
